[project]
scalaVersion = "2.13.2"
scalaOptions = [
  "-deprecation", # Emit warning and location for usages of deprecated APIs.
  "-encoding",
  "UTF-8",         # yes, this is 2 args. Specify character encoding used by source files.
  "-explaintypes", # Explain type errors in more detail.
  "-feature",      # Emit warning and location for usages of features that should be imported explicitly.
  "-language:existentials",
  "-language:higherKinds",
  "-language:implicitConversions",
  "-unchecked",
  "-Xlint",
  "-Yrangepos",              # required by SemanticDB compiler plugin
  "-Ywarn-dead-code",        # Warn when dead code is identified.
  "-Ywarn-extra-implicit",   # Warn when more than one implicit parameter section is defined.
  "-Ywarn-numeric-widen",    # Warn when numerics are widened.
  "-Ywarn-unused:implicits", # Warn if an implicit parameter is unused.
  "-Ywarn-unused:imports",   # Warn if an import selector is not referenced.
  "-Ywarn-unused:locals",    # Warn if a local definition is unused.
  "-Ywarn-unused:params",    # Warn if a value parameter is unused.
  "-Ywarn-unused:patvars",   # Warn if a variable bound in a pattern is unused.
  "-Ywarn-unused:privates",  # Warn if a private member is unused.
  "-Ywarn-value-discard"     # Warn when non-Unit expression results are unused.
]
testFrameworks = ["org.scalatest.tools.Framework"]

[module.demoseed.jvm]
root = "."
resources = [
  "src/main/resources"
]
sources = [
  "src/main/scala",
  "src/main/java"
]
scalaDeps = [
  ["io.circe", "circe-core", "0.13.0"]
]


[module.demoseed.test.jvm]
sources = [
  "src/test/scala",
  "src/test/java"
]
resources = [
  "src/test/resources"
]
scalaDeps = [["org.scalatest", "scalatest", "3.2.0"]]